all:
	make -C base  	
	make -C thread  
	make -C logger  
	make -C other  	
	make -C plugin 
	make -C perf

clean:
	make -C base  	clean
	make -C logger  clean
	make -C other  	clean
	make -C thread  clean
	make -C plugin  clean
	make -C perf 	clean
